# Do not edit this file, copy this file & rename it to const.py. Any format error will result in not getting start or help message.

from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton


#use the same format for name & user_id placeholders
START_MSG = """
𝖧𝖾𝗅𝗅𝗈 **[{}](tg://user?id={})**, 𝖭𝗂𝖼𝖾 𝖳𝗈 𝖬𝖾𝖾𝗍 𝖸𝗈𝗎 🎊
𝖸𝗈𝗎 𝖢𝖺𝗇 𝖲𝖾𝖺𝗋𝖼𝗁 𝖥𝗈𝗋 𝖠𝗇𝗒 𝖬𝖾𝖽𝗂𝖺 𝖥𝗂𝗅𝖾𝗌 𝖳𝗁𝗋𝗈𝗎𝗀𝗁 𝖬𝖾 😊

𝖭𝗈𝗍𝖾: 𝖠𝗅𝗅 𝗍𝗁𝖾 𝖿𝗂𝗅𝖾𝗌 𝗂𝗇 𝗍𝗁𝗂𝗌 𝖻𝗈𝗍 𝖺𝗋𝖾 𝖿𝗋𝖾𝖾𝗅𝗒 𝖺𝗏𝖺𝗂𝗅𝖺𝖻𝗅𝖾 𝗈𝗇 𝗍𝗁𝖾 𝗂𝗇𝗍𝖾𝗋𝗇𝖾𝗍 𝗈𝗋 𝗉𝗈𝗌𝗍𝖾𝖽 𝖻𝗒 𝗌𝗈𝗆𝖾𝖻𝗈𝖽𝗒 𝖾𝗅𝗌𝖾.
𝖳𝗁𝗂𝗌 𝖻𝗈𝗍 𝗂𝗌 𝗂𝗇𝖽𝖾𝗑𝗂𝗇𝗀 𝖿𝗂𝗅𝖾𝗌 𝗐𝗁𝗂𝖼𝗁 𝖺𝗋𝖾 𝖺𝗅𝗋𝖾𝖺𝖽𝗒 𝗎𝗉𝗅𝗈𝖺𝖽𝖾𝖽 𝗈𝗇 𝖳𝖾𝗅𝖾𝗀𝗋𝖺𝗆 𝖿𝗈𝗋 𝖾𝖺𝗌𝖾 𝗈𝖿 𝗌𝖾𝖺𝗋𝖼𝗁𝗂𝗇𝗀.
"""

HELP_MSG = """
**You can find the bot commands here.**
**User Commands:-**
/help - __Show this help message__
/settings - __Toggle settings of Precise Mode and Button Mode__
`Precise Mode:` 
- __If Enabled, bot will match the word & return results with only the exact match__
- __If Disabled, bot will match the word & return all the results containing the word__    
`Result Mode:` 
- __If Button, bot will return results in button format__
- __If List, bot will return results in list format__
- __If HyperLink, bot will return results in hyperlink format__

**Admin Commands:-**
/logs - __Get logs as a file__
/server - __Get server stats__
/restart - __Restart the bot__
/stats - __Get bot user stats__
/broadcast - __Reply to a message to send that to all bot users__
/index - __Start indexing a database channel (bot must be admin of the channel if that is provate channel)__
__You can just forward the message from database channel for starting indexing, no need to use the /index command__
/delete - __Reply to a file to delete it from database__
/autodelete - __Set file auto delete time in seconds__
/repairmode - __Enable or disable repair mode - If on, bot will not send any files__
/customcaption - __Set custom caption for files__
/adminsettings - __Get current admin settings__
/ban - __Ban a user from bot__ - `/ban user_id`
/unban - __Unban a user from bot__ - `/unban user_id`
/addfilter - __Add a text filter__ - `/addfilter filter message` __or__ `/addfilter "filter multiple words" message` __(If a filter is there, bot will send the filter rather than file)__
/delfilter - __Delete a text filter__ - `/delfilter filter`
/listfilters - __List all filters currently added in the bot__
/forcesub - __Set force subscribe channel__ - `/forcesub channel_id` __Bot must be admin of that channel (Bot will create a new invite link for that channel)__
/checklink - __Check invite link for force subscribe channel__
/total - __Get count of total files in DB__
"""


START_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🆘 Help", callback_data="help_cb"),
            InlineKeyboardButton(
                "👨‍💻 Source Code", url="https://github.com/EL-Coders/mediafinder"
            ),
        ]
    ]
)

HELP_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🔙 Back", callback_data="back_m"),
        ],
    ]
)
